// ======================================================
// PRICING — logs estruturados (Suse7)
// ======================================================
// Eventos acionáveis para agregador / grep. Não substitui métricas de produto.
// ======================================================

/** @typedef {"warn" | "info"} PricingLogLevel */

export const PRICING_LOG_LEVEL = /** @type {const} */ ({
  WARN: "warn",
  INFO: "info",
});

/**
 * Códigos estáveis para filtro (ex.: `grep PRICING_FEE_BASE_MISMATCH`).
 * Prefixo PRICING_* evita colisão com outros domínios.
 */
export const PRICING_EVENT_CODE = /** @type {const} */ ({
  INVALID_LISTING_PRICE: "INVALID_LISTING_PRICE",
  INVALID_PROMOTION_DATA: "INVALID_PROMOTION_DATA",
  INVALID_PROMOTION_NON_POSITIVE: "INVALID_PROMOTION_NON_POSITIVE",
  INVALID_PROMOTION_NOT_BELOW_LISTING: "INVALID_PROMOTION_NOT_BELOW_LISTING",
  PROMOTION_HINT_MISMATCH: "PROMOTION_HINT_MISMATCH",
  PROMOTION_DATA_OVERRIDES_HINT: "PROMOTION_DATA_OVERRIDES_HINT",
  PRICING_FALLBACK_APPLIED: "PRICING_FALLBACK_APPLIED",
  FEE_BASE_MISMATCH: "FEE_BASE_MISMATCH",
  LISTING_PRICES_INCOMPLETE: "LISTING_PRICES_INCOMPLETE",
  NEGATIVE_SALE_FEE_BLOCKED: "NEGATIVE_SALE_FEE_BLOCKED",
  INVALID_SHIPPING_COST: "INVALID_SHIPPING_COST",
  /** Valor monetário de envio/custo ML obtido de payload ou health. */
  SHIPPING_COST_FROM_ML: "SHIPPING_COST_FROM_ML",
  SHIPPING_COST_RESOLVED_FROM_PAYLOAD: "SHIPPING_COST_RESOLVED_FROM_PAYLOAD",
  SHIPPING_COST_RESOLVED_FROM_ENRICH: "SHIPPING_COST_RESOLVED_FROM_ENRICH",
  SHIPPING_COST_OFFICIAL_CANDIDATE_FOUND: "SHIPPING_COST_OFFICIAL_CANDIDATE_FOUND",
  SHIPPING_COST_OFFICIAL_SELECTED: "SHIPPING_COST_OFFICIAL_SELECTED",
  SHIPPING_COST_INVALID_ML_ITEM_SKIPPED: "SHIPPING_COST_INVALID_ML_ITEM_SKIPPED",
  SHIPPING_COST_OFFICIAL_OVERRULED_ML_ITEM: "SHIPPING_COST_OFFICIAL_OVERRULED_ML_ITEM",
  SHIPPING_OPTIONS_FREE_FETCH_STARTED: "SHIPPING_OPTIONS_FREE_FETCH_STARTED",
  SHIPPING_OPTIONS_FREE_FETCH_SUCCESS: "SHIPPING_OPTIONS_FREE_FETCH_SUCCESS",
  SHIPPING_OPTIONS_FREE_FETCH_FAILED: "SHIPPING_OPTIONS_FREE_FETCH_FAILED",
  SHIPPING_OPTIONS_FREE_VALUE_SELECTED: "SHIPPING_OPTIONS_FREE_VALUE_SELECTED",
  SHIPPING_OPTIONS_FREE_VALUE_MISSING: "SHIPPING_OPTIONS_FREE_VALUE_MISSING",
  SHIPPING_COST_OFFICIAL_SELECTED_FROM_SHIPPING_OPTIONS: "SHIPPING_COST_OFFICIAL_SELECTED_FROM_SHIPPING_OPTIONS",
  /** shipping_options/free guardado só como referência (não canônico Raio-X). */
  SHIPPING_COST_AUXILIARY_SIMULATION_STORED: "SHIPPING_COST_AUXILIARY_SIMULATION_STORED",
  /** GAP (sale−fee−net) válido prevalece sobre listing_prices na linha. */
  SHIPPING_COST_GAP_PRIORITY_OVER_LISTING_PRICES: "SHIPPING_COST_GAP_PRIORITY_OVER_LISTING_PRICES",
  /** Candidatos de frete (listing_prices × sale_fee_details × shipping_options/free) — trace pontual / diagnóstico. */
  SHIPPING_COST_RESOLUTION_CANDIDATES_TRACE: "SHIPPING_COST_RESOLUTION_CANDIDATES_TRACE",
  /** sale_fee_details não vazio mas parser de logística não extraiu valor (auditoria / gap de formato). */
  SHIPPING_COST_PARSE_FAILED_FROM_SALE_FEE_DETAILS: "SHIPPING_COST_PARSE_FAILED_FROM_SALE_FEE_DETAILS",
  SHIPPING_COST_GAP_FALLBACK_SELECTED: "SHIPPING_COST_GAP_FALLBACK_SELECTED",
  SHIPPING_COST_GAP_FALLBACK_REJECTED: "SHIPPING_COST_GAP_FALLBACK_REJECTED",
  SHIPPING_COST_CONTEXT_MISMATCH_DETECTED: "SHIPPING_COST_CONTEXT_MISMATCH_DETECTED",
  SHIPPING_COST_VALUE_MISMATCH_WITH_OFFICIAL: "SHIPPING_COST_VALUE_MISMATCH_WITH_OFFICIAL",
  SHIPPING_COST_PERSIST_SKIPPED_INCONSISTENT: "SHIPPING_COST_PERSIST_SKIPPED_INCONSISTENT",
  /** Linha logística / taxa embutida no breakdown `sale_fee_details` (Raio-X ML). */
  SHIPPING_COST_FROM_SALE_FEE_DETAILS: "SHIPPING_COST_FROM_SALE_FEE_DETAILS",
  /** Contexto comprador (free_shipping) resolvido. */
  SHIPPING_CONTEXT_RESOLVED: "SHIPPING_CONTEXT_RESOLVED",
  /** Nenhum valor aplicável após payload, health e gap. */
  SHIPPING_COST_MISSING: "SHIPPING_COST_MISSING",
  SHIPPING_COST_UNRESOLVED: "SHIPPING_COST_UNRESOLVED",
  /** Valor inválido (ex.: negativo). */
  INVALID_SHIPPING_COST_VALUE: "INVALID_SHIPPING_COST_VALUE",
  SHIPPING_COST_INCONSISTENT_SKIPPED: "SHIPPING_COST_INCONSISTENT_SKIPPED",
  /** Dedução inferida por sale − fee − net_receivable (alinhamento ao “Você recebe” ML). */
  SHIPPING_COST_GAP_FROM_NET_RECEIVABLE: "SHIPPING_COST_GAP_FROM_NET_RECEIVABLE",
  SHIPPING_COST_INFERRED_FROM_FINANCIAL_GAP: "SHIPPING_COST_INFERRED_FROM_FINANCIAL_GAP",
  /** Alias operacional: fallback numérico aplicado (mesmo fluxo que GAP). */
  SHIPPING_COST_FALLBACK_APPLIED: "SHIPPING_COST_FALLBACK_APPLIED",
  /** free_shipping ausente — assume buyer_pays. */
  SHIPPING_CONTEXT_INFERRED_DEFAULT: "SHIPPING_CONTEXT_INFERRED_DEFAULT",
  /** @deprecated faixa de preço removida — mantido só para logs legados */
  SHIPPING_FIXED_FEE_CONFLICT: "SHIPPING_FIXED_FEE_CONFLICT",
  FIXED_FEE_RANGE_APPLIED: "FIXED_FEE_RANGE_APPLIED",
  SHIPPING_COST_APPLIED: "SHIPPING_COST_APPLIED",
  SHIPPING_OR_FIXED_FEE_FALLBACK: "SHIPPING_OR_FIXED_FEE_FALLBACK",
  INVALID_SALE_PRICE_FOR_FIXED_FEE: "INVALID_SALE_PRICE_FOR_FIXED_FEE",
  // Cenários de precificação — GET /items/:id/shipping_options (zip + price do cenário)
  ML_SHIPPING_OPTIONS_FETCH_START: "ML_SHIPPING_OPTIONS_FETCH_START",
  ML_SHIPPING_OPTIONS_FETCH_OK: "ML_SHIPPING_OPTIONS_FETCH_OK",
  ML_SHIPPING_OPTIONS_FETCH_FAIL: "ML_SHIPPING_OPTIONS_FETCH_FAIL",
  ML_SCENARIO_SHIPPING_RESOLVED: "ML_SCENARIO_SHIPPING_RESOLVED",
  ML_SCENARIO_SHIPPING_FALLBACK_NET_PROCEEDS: "ML_SCENARIO_SHIPPING_FALLBACK_NET_PROCEEDS",
  ML_SCENARIO_SHIPPING_FALLBACK_PERSISTED: "ML_SCENARIO_SHIPPING_FALLBACK_PERSISTED",
  ML_SCENARIO_SHIPPING_ESTIMATED: "ML_SCENARIO_SHIPPING_ESTIMATED",
  ML_PROMOTION_SUBSIDY_RESOLVED: "ML_PROMOTION_SUBSIDY_RESOLVED",
  ML_PROMOTION_SUBSIDY_FALLBACK: "ML_PROMOTION_SUBSIDY_FALLBACK",
  ML_SCENARIO_FINANCIALS_RESOLVED: "ML_SCENARIO_FINANCIALS_RESOLVED",
  ML_PROMOTION_SCENARIO_SKIPPED_INVALID: "ML_PROMOTION_SCENARIO_SKIPPED_INVALID",
  ML_PROMOTION_SCENARIOS_DIAGNOSTIC: "ML_PROMOTION_SCENARIOS_DIAGNOSTIC",
  ML_PROMOTION_SCENARIO_DEBUG: "ML_PROMOTION_SCENARIO_DEBUG",
  /** Colisão na deduplicação de cenários promo (auditoria — chave composta promotion_id+vigência). */
  ML_PROMOTION_DEDUPE_DEBUG: "ML_PROMOTION_DEDUPE_DEBUG",
  /** Falha ao processar uma promoção no pipeline de cenários (não derruba o endpoint se tratado). */
  ML_PRICING_SCENARIOS_PIPELINE_ERROR: "ML_PRICING_SCENARIOS_PIPELINE_ERROR",
});

/**
 * @param {PricingLogLevel} level
 * @param {string} code
 * @param {Record<string, unknown>} payload
 */
/**
 * Serialização segura para console (evita throw por BigInt / referência circular em payloads ML).
 * @param {unknown} value
 */
function safeJsonLine(value) {
  try {
    return JSON.stringify(value, (_k, v) => {
      if (typeof v === "bigint") return v.toString();
      return v;
    });
  } catch {
    return JSON.stringify({
      suse7_log_lane: "pricing",
      level: "warn",
      code: "LOG_SERIALIZE_FALLBACK",
      ts: new Date().toISOString(),
      message: "payload não serializável",
    });
  }
}

export function logPricingEvent(level, code, payload) {
  const line = {
    suse7_log_lane: "pricing",
    level,
    code,
    ts: new Date().toISOString(),
    ...payload,
  };
  const s = safeJsonLine(line);
  if (level === PRICING_LOG_LEVEL.WARN) console.warn(s);
  else console.info(s);
}
