// ======================================================================
// Sanitização de ad_titles para exibição / edição (Gerador de títulos)
// Remove fallback legado: 1 título idêntico ao product_name (import ML antigo).
// ======================================================================

import { normalizeTitle, normalizeTitleKey } from "../domain/AdTitlesDomainService.js";

/**
 * @param {unknown} item
 * @returns {{ id: string; value: string; manual?: boolean; source?: string } | null}
 */
function normalizarItemAdTitle(item) {
  if (item == null) return null;
  const value = normalizeTitle(String(item?.value ?? item?.title ?? item ?? ""));
  if (!value) return null;
  const id =
    item?.id != null && String(item.id).trim() !== ""
      ? String(item.id).trim()
      : typeof crypto !== "undefined" && crypto.randomUUID
        ? crypto.randomUUID()
        : `t_${Date.now()}_${Math.random().toString(36).slice(2)}`;
  return {
    id,
    value,
    manual: item?.manual === true,
    source: item?.source != null ? String(item.source) : undefined,
  };
}

/**
 * @param {{ manual?: boolean; source?: string }} item
 */
function tituloCriadoManualmentePeloSeller(item) {
  if (item.manual === true) return true;
  const source = item.source != null ? String(item.source).trim().toLowerCase() : "";
  return source === "seller" || source === "manual";
}

/**
 * Fallback antigo (import ML / create v1): único título = cópia do nome do produto.
 * @param {Array<{ id: string; value: string; manual?: boolean; source?: string }>} titles
 * @param {unknown} productName
 */
function isLegacyAutoGeneratedAdTitles(titles, productName) {
  if (!Array.isArray(titles) || titles.length !== 1) return false;
  const only = titles[0];
  if (tituloCriadoManualmentePeloSeller(only)) return false;
  const nameKey = normalizeTitleKey(String(productName ?? ""));
  const titleKey = normalizeTitleKey(only.value);
  if (!nameKey || !titleKey) return false;
  return nameKey === titleKey;
}

/**
 * @param {unknown} adTitles
 * @param {unknown} productName
 * @returns {{ id: string; value: string }[]}
 */
export function sanitizeAdTitlesForDisplay(adTitles, productName) {
  let arr = [];
  if (Array.isArray(adTitles)) {
    arr = adTitles;
  } else if (typeof adTitles === "string" && adTitles.trim()) {
    try {
      const parsed = JSON.parse(adTitles);
      arr = Array.isArray(parsed) ? parsed : [];
    } catch {
      arr = [];
    }
  }

  const titles = arr.map(normalizarItemAdTitle).filter(Boolean);
  if (titles.length === 0) return [];
  if (isLegacyAutoGeneratedAdTitles(titles, productName)) return [];

  return titles.map(({ id, value }) => ({ id, value }));
}
